# Generated by Django 6.0.2 on 2026-03-11 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0002_add_aliases_to_entities"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="book_unique_name",
        ),
        migrations.RemoveConstraint(
            model_name="game",
            name="game_unique_name",
        ),
        migrations.RemoveConstraint(
            model_name="movie",
            name="movie_unique_name",
        ),
        migrations.RemoveConstraint(
            model_name="show",
            name="show_unique_name",
        ),
    ]
