# Generated by Django 6.0.2 on 2026-03-17 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingobject",
            name="notes",
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
